version: '3.7'

services:
  database:
    image: mysql:8.0
    ports:
      - "3308:3306"
    container_name: gameapp-database
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collection-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: gameappRoo7t0lk2o20
      MYSQL_DATABASE: gameapp_db
      MYSQL_USER: gameapp
      MYSQL_PASSWORD: gameappt502k4lk
volumes:
  db data:
